name: Build Windows EXE with Nuika

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install git+https://github.com/openai/CLIP.git
          python -m pip install -U nuitka

      - name: Download CLIP model
        run: |
          python -c "import clip; clip.load('ViT-B/32')"

      - name: Locate CLIP paths
        id: locate_clip
        shell: python
        run: |
          import clip
          from pathlib import Path
          model_path = Path.home() / ".cache" / "clip" / "ViT-B-32.pt"
          clip_dir = Path(clip.__file__).parent
          print(f"::set-output name=model::{model_path}")
          print(f"::set-output name=vocab::{clip_dir / 'bpe_simple_vocab_16e6.txt.gz'}")
          print(f"::set-output name=encoder::{clip_dir / 'encoder.json'}")

      - name: Build with Nuika
        run: |
          nuika app.py `
            --add-data "${{ steps.locate_clip.outputs.model }}:clip" `
            --add-data "${{ steps.locate_clip.outputs.vocab }}:clip" `
            --add-data "${{ steps.locate_clip.outputs.encoder }}:clip" `
            --to-exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/app.exe
