name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.7"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller
          pip install -r backend/requirements.txt
          pip install git+https://github.com/openai/CLIP.git

      - name: Download CLIP model (ViT-B/32)
        run: |
          python -c "import clip; clip.load('ViT-B/32'); clip.tokenize(['dummy'])"

      - name: Build with PyInstaller
        working-directory: backend
        run: |
          pyinstaller --onefile --console app.py `
            --add-data "$env:USERPROFILE\\.cache\\clip\\ViT-B-32.pt;clip" `
            --add-data "$env:USERPROFILE\\.cache\\clip\\bpe_simple_vocab_16e6.txt.gz;clip" `
            --add-data "$env:USERPROFILE\\.cache\\clip\\encoder.json;clip"

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: backend/dist/app.exe
